const stockProductos = [
    {id: 1, nombre: "PLACA DE VIDEO POWERCOLOR", tipo: "Placa de Video", cantidad: 1, modelo: "RED DRAGON RX 550 4GB GDDR5 LP S", precio: 67999, img: './img/placaVideo1.png'},
    {id: 2, nombre: "PLACA DE VIDEO GIGABYTE", tipo: "Placa de Video", cantidad: 1, modelo: "GV-R65XTEAGLE-4GD ", precio: 88999, img: './img/placaVideo2.png'},
    {id: 3, nombre: "PLACA DE VIDEO PALIT", tipo: "Placa de Video", cantidad: 1, modelo: "NVIDIA GEFORCE GTX 1660 6GB", precio: 109999, img: './img/placaVideo3.png'},
    {id: 4, nombre: "PLACA DE VIDEO POWERCOLOR", tipo: "Placa de Video", cantidad: 1, modelo: "RX6600 XT FIGHTER 8GB GDDR6", precio: 154999, img: './img/placaVideo4.png'},
    {id: 5, nombre: "PLACA DE VIDEO POWERCOLOR", tipo: "Placa de Video", cantidad: 1, modelo: "AMD RADEON RX 6700 XT RED DEVIL 12GB", precio: 204999, img: './img/placaVideo5.png'},
    {id: 6, nombre: "PLACA DE VIDEO PALIT", tipo: "Placa de Video", cantidad: 1, modelo: "NVIDIA GEFORCE RTX 3060 TI DUAL 8GB GDDR6 256BIT LHR", precio: 214999, img: './img/placaVideo6.png'},
    {id: 7, nombre: "MICROPROCESADOR INTEL CORE I5", tipo: "Procesador", cantidad: 1, modelo: "11400F ROCKET LAKE 6/12 4.40GHZ 12MB", precio: 59990, img: './img/procesador1.png'},
    {id: 8, nombre: "MICROPROCESADOR CPU AMD RYZEN 5", tipo: "Procesador", cantidad: 1, modelo: "5600 6/12 ZEN3", precio: 74990, img: './img/procesador2.png'},
    {id: 9, nombre: "MICROPROCESADOR INTEL CORE I7", tipo: "Procesador", cantidad: 1, modelo: "10700F COMETLAKE 4.8GHZ S/GRAFICOS", precio: 94990, img: './img/procesador3.png'},
    {id: 10, nombre: "MICROPROCESADOR AMD RYZEN 7", tipo: "Procesador", cantidad: 1, modelo: "5700G 4.6 GHZ AM4", precio: 109990, img: './img/procesador4.png'},
    {id: 11, nombre: "MICROPROCESADOR INTEL CORE I9", tipo: "Procesador", cantidad: 1, modelo: "10900F COMETLAKE 5.2GHZ 20MB", precio: 164990, img: './img/procesador5.png'},
    {id: 12, nombre: "MICROPROCESADOR AMD RYZEN 9", tipo: "Procesador", cantidad: 1, modelo: "5900X 12/24 4.8GHZ S/G S/C ZEN3", precio: 189990, img: './img/procesador6.png'},
    {id: 13, nombre: "MOTHERBOARD GIGABYTE", tipo: "Motheboard", cantidad: 1, modelo: "H510M S2H V2 MATX 1200", precio: 31999, img: './img/motherboard1.png'},
    {id: 14, nombre: "MOTHERBOARD ASUS", tipo: "Motheboard", cantidad: 1, modelo: "PRIME H610M-E D4 S1700", precio: 34999, img: './img/motherboard2.png'},
    {id: 15, nombre: "MOTHERBOARD MSI", tipo: "Motheboard", cantidad: 1, modelo: "B560M-A PRO MATX S1200", precio: 35999, img: './img/motherboard3.png'},
    {id: 16, nombre: "MOTHERBOARD ASROCK", tipo: "Motheboard", cantidad: 1, modelo: "H510 PRO BTC+ MINING S1200 DDR4", precio: 53999, img: './img/motherboard4.png'},
    {id: 17, nombre: "MOTHERBOARD GIGABYTE", tipo: "Motheboard", cantidad: 1, modelo: "B660M AORUS PRO AX DDR4 M-ATX S1700", precio: 69999, img: './img/motherboard5.png'},
    {id: 18, nombre: "MOTHERBOARD MSI", tipo: "Motheboard", cantidad: 1, modelo: "PRO Z790-P WIFI DDR4 S1700", precio: 98999, img: './img/motherboard6.png'},
    {id: 19, nombre: "FUENTE COOLER MASTER", tipo: "Fuente", cantidad: 1, modelo: "500W 80+ BRONZE MWE", precio: 24990, img: './img/fuente1.png'},
    {id: 20, nombre: "FUENTE CORSAIR", tipo: "Fuente", cantidad: 1, modelo: "550W CX550F 80+ BRONZE MODULAR WHITE", precio: 25990, img: './img/fuente2.png'},
    {id: 21, nombre: "FUENTE AEROCOOL CYLON", tipo: "Fuente", cantidad: 1, modelo: "500W RGB 80+ BRONZE", precio: 26990, img: './img/fuente3.png'},
    {id: 22, nombre: "FUENTE AZZA", tipo: "Fuente", cantidad: 1, modelo: "750W 80+ BRONZE ARGB", precio: 27990, img: './img/fuente4.png'},
    {id: 23, nombre: "FUENTE GIGABYTE", tipo: "Fuente", cantidad: 1, modelo: "50W 80+ GOLD AP750GM AORUS MODULAR", precio: 37990, img: './img/fuente5.png'},
    {id: 24, nombre: "FUENTE REDRAGON", tipo: "Fuente", cantidad: 1, modelo: "850W 80+ GOLD", precio: 42990, img: './img/fuente6.png'},
]